/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Mod {
  'content' : Array<string>,
  'name' : string,
  'description' : string,
}
export interface Subject { 'id' : bigint, 'mods' : Array<Mod>, 'name' : string }
export interface SubjectCategory {
  'subjects' : Array<Subject>,
  'name' : string,
}
export interface TimetableEntry {
  'startTime' : bigint,
  'duration' : bigint,
  'subjectName' : string,
  'dayOfWeek' : string,
  'subjectId' : bigint,
  'category' : string,
  'classType' : string,
}
export interface _SERVICE {
  'addTimetableEntry' : ActorMethod<
    [bigint, string, string, string, string, bigint, bigint],
    undefined
  >,
  'clearTimetable' : ActorMethod<[], undefined>,
  'getAllCategories' : ActorMethod<[], Array<SubjectCategory>>,
  'getAllCategoryNames' : ActorMethod<[], Array<string>>,
  'getAllSubjects' : ActorMethod<[], Array<Subject>>,
  'getCategoryByName' : ActorMethod<[string], [] | [SubjectCategory]>,
  'getCategoryCount' : ActorMethod<[], bigint>,
  'getModFromSubjects' : ActorMethod<[string, bigint, string], [] | [Mod]>,
  'getModsFromSubject' : ActorMethod<[string, bigint], [] | [Array<Mod>]>,
  'getSubjectsByCategoryIndex' : ActorMethod<[bigint], [] | [Array<Subject>]>,
  'getTimetable' : ActorMethod<[], Array<TimetableEntry>>,
  'getTimetableByDay' : ActorMethod<[string], Array<TimetableEntry>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];