/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Mod = IDL.Record({
  'content' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Subject = IDL.Record({
  'id' : IDL.Nat,
  'mods' : IDL.Vec(Mod),
  'name' : IDL.Text,
});
export const SubjectCategory = IDL.Record({
  'subjects' : IDL.Vec(Subject),
  'name' : IDL.Text,
});
export const TimetableEntry = IDL.Record({
  'startTime' : IDL.Nat,
  'duration' : IDL.Nat,
  'subjectName' : IDL.Text,
  'dayOfWeek' : IDL.Text,
  'subjectId' : IDL.Nat,
  'category' : IDL.Text,
  'classType' : IDL.Text,
});

export const idlService = IDL.Service({
  'addTimetableEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'clearTimetable' : IDL.Func([], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(SubjectCategory)], ['query']),
  'getAllCategoryNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
  'getCategoryByName' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SubjectCategory)],
      ['query'],
    ),
  'getCategoryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getModFromSubjects' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Opt(Mod)],
      ['query'],
    ),
  'getModsFromSubject' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(IDL.Vec(Mod))],
      ['query'],
    ),
  'getSubjectsByCategoryIndex' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(IDL.Vec(Subject))],
      ['query'],
    ),
  'getTimetable' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
  'getTimetableByDay' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TimetableEntry)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Mod = IDL.Record({
    'content' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const Subject = IDL.Record({
    'id' : IDL.Nat,
    'mods' : IDL.Vec(Mod),
    'name' : IDL.Text,
  });
  const SubjectCategory = IDL.Record({
    'subjects' : IDL.Vec(Subject),
    'name' : IDL.Text,
  });
  const TimetableEntry = IDL.Record({
    'startTime' : IDL.Nat,
    'duration' : IDL.Nat,
    'subjectName' : IDL.Text,
    'dayOfWeek' : IDL.Text,
    'subjectId' : IDL.Nat,
    'category' : IDL.Text,
    'classType' : IDL.Text,
  });
  
  return IDL.Service({
    'addTimetableEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'clearTimetable' : IDL.Func([], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(SubjectCategory)], ['query']),
    'getAllCategoryNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllSubjects' : IDL.Func([], [IDL.Vec(Subject)], ['query']),
    'getCategoryByName' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SubjectCategory)],
        ['query'],
      ),
    'getCategoryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getModFromSubjects' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Opt(Mod)],
        ['query'],
      ),
    'getModsFromSubject' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(IDL.Vec(Mod))],
        ['query'],
      ),
    'getSubjectsByCategoryIndex' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(IDL.Vec(Subject))],
        ['query'],
      ),
    'getTimetable' : IDL.Func([], [IDL.Vec(TimetableEntry)], ['query']),
    'getTimetableByDay' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TimetableEntry)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };